### ISSUE TITLE
How to build from source

### ISSUE THREAD

**Issue by Ami-OS** [Pong420/videojs-plus#19]
Hi, I want to build from source, but I have no experience with `yarn`

What do I have to do?

**Comment by Pong420** [comment]
Install yarn
https://yarnpkg.com/getting-started/install
https://classic.yarnpkg.com/en/docs/install

run 
```
# install all node_modules
yarn

# build 
yarn build
```

**Comment by Ami-OS** [comment]
Oh, I get error on Ubuntu 20.04.1 LTS

```
tester@tester-virtual-machine:~/Downloads/source/videojs-plus$ yarn
yarn install v1.22.5
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.33s.
tester@tester-virtual-machine:~/Downloads/source/videojs-plus$ yarn build
yarn run v1.22.5
$ rimraf dist
$ rollup -c rollup.config.js

source/index.js → dist/videojs-plus.umd.js, dist/videojs-plus.es.js...
created dist/videojs-plus.umd.js, dist/videojs-plus.es.js in 1.9s

source/Plugin/AudioTrack//AudioTrack.js → dist/plugins/audio-track/index.js, dist/plugins/audio-track/audio-track.es.js...
created dist/plugins/audio-track/index.js, dist/plugins/audio-track/audio-track.es.js in 268ms

source/Plugin/Autoplay//Autoplay.js → dist/plugins/autoplay/index.js, dist/plugins/autoplay/autoplay.es.js...
[!] Error: Could not resolve entry module (source/Plugin/Autoplay//Autoplay.js).
Error: Could not resolve entry module (source/Plugin/Autoplay//Autoplay.js).
    at error (/home/tester/Downloads/source/videojs-plus/node_modules/rollup/dist/shared/rollup.js:10399:30)
    at resolveId.then.resolveIdResult (/home/tester/Downloads/source/videojs-plus/node_modules/rollup/dist/shared/rollup.js:16925:20)

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What am I missing?

**Comment by Pong420** [comment]
please pull the latest commit and try again

**Comment by Ami-OS** [comment]
Oh, it succeeded, thx
